# Generated by Django 4.1.5 on 2023-01-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='아이디'),
        ),
    ]
