# Generated by Django 4.1.5 on 2023-01-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='member',
            name='user_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='아이디'),
        ),
    ]
